name: Update WARP

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/**'
      - 'yxip/**'
      - 'warp.py'
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress

    - name: Run script
      run: python warp.py

    - name: Commit update
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto update
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
